on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: dotnet build --configuration Release src/HealthCheck.sln
    - name: Test
      run: dotnet test --configuration Release --no-build src/HealthCheck.sln
    - name: Pack
      run: dotnet pack --configuration Release --no-build src/HealthCheck.sln -o dist
    - name: Push
      run: dotnet nuget push dist/*.nupkg --source https://nuget.pkg.github.com/cerberix/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUGET_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
